### ISSUE TITLE
rawText

### ISSUE THREAD

**Issue by dudil** [yahoojapan/SwiftyXMLParser#11]
How could you print rawText of the XML?
This is needed to debug new source of XML to understand how to parse it.

**Comment by kazuhiro4949** [comment]
This doesn't have the method to output rawText. 
You can print XML of Data type as follows.

```swift
let data = Data()
print(String(data: data, encoding: .utf8)!)
```

If it is not enough for you, please comment the detail.

**Comment by dudil** [comment]
yes I understand.
I was referring to the same API as you might find on SwiftyJSON:
https://github.com/SwiftyJSON/SwiftyJSON#raw-object

Still - thank you so much for that solution, it is indeed very easy to use 🥇

**Comment by kazuhiro4949** [comment]
I'm glad the problem was solved 😃 
We didn't implement some utilities SwiftyJSON has, and keeps this library to minimum.
If you wanna some features, we welcome your pull-request 😄

**Comment by dudil** [comment]
Sure - will do that 😄
ありがとうございました
