### ISSUE TITLE
How to enumerate children of a node

### ISSUE THREAD

**Issue by rlaguilar** [yahoojapan/SwiftyXMLParser#15]
Hi there.
I have the following XML:
```
<list>
   <string>Item1</string>
   <markdown>Item2</markdown>
</list>
```
Note that inside the list may be an arbitrary amount of items of different kinds. How can I enumerate them?

**Comment by kazuhiro4949** [comment]
Hi @rlaguilar :)

You can access internal elements with the following code.
```swift
let doc = """
    <list>
        <string>Item1</string>
        <markdown>Item2</markdown>
    </list>
""".data(using: .utf8)!

let xml = XML.parse(doc)

let listElement = xml["list"].element // => accesses internal element in "list" node

// If it as child elements, you can get [Element] with the property.
guard let childElements = listElement?.childElements else {
    return
}

// you can access arbitrary child elements from it.
for element in childElements {
    print(element.name, element.text) // print (string, Item1) and (markdown, Item2)
}
```

Currently, this library doesn't have a ease way to access arbitrary name. 
But the case you faced should be not unusual. I will consider the better interface. (maybe syntax sugar of the above code) (of course, welcome to your pull-request too)

**Comment by rlaguilar** [comment]
Hi @kazuhiro4949 
Thanks for your helpful response. Your solution works very well for me since what I need to do is just to explore the XML tree to build a custom object from it. 
Feel free to close this issue.
