### ISSUE TITLE
Printing complete XML

### ISSUE THREAD

**Issue by rat-moonshine** [yahoojapan/SwiftyXMLParser#16]
Hi there!

How do I print the complete XML (irrespective of any specific element) as string that I received from web service? 

Thanks!

**Comment by kazuhiro4949** [comment]
@rat-moonshine Hi!

There is no need to provide the feature in this library, because you can easily print it by the standard api.

```swift
let data: Data = "<xml><string>string</string></xml>".data(using: .utf8) // Data object
print(String(data: data, encoding: .utf8)!)  // You can print xml string from Data type (e.g. NSURLSession's completeHandler)
```

If you have any trouble to the above solution. feel free to contact us :)

**Comment by rat-moonshine** [comment]
That was easy and effective! Perhaps you want to include anyway a `toXMLString()` function seeing nooby like me :P

Thank you!
