### ISSUE TITLE
Unicode Characters

### ISSUE THREAD

**Issue by NIESolutions** [yahoojapan/SwiftyXMLParser#25]
While using SwiftyXMLParser with a string with unicode characters inside, the parser automatically stops at the (probably) unknown message.

Inside Message was something like this:
`<xmlopening>@ß123\u{1c}</xmlopening>`

I think the \u{1c} is a character caused by application / data transfer error.

After this line in file, the rest of XML will be ignored.

**Comment by kazuhiro4949** [comment]
@NIESolutions
 I'm sorry for my late. 

 XMLParser cannot parse '\u{1c}', because it is invalid as XML Document.  Refer to the link.

https://stackoverflow.com/questions/404107/why-are-control-characters-illegal-in-xml-1-0

You have to escape them with percent encoding to make a valid XML document. 
 
```swift
let str2 = "<xmlopening>@ß123\u{1c}</xmlopening>"
    .addingPercentEncoding(withAllowedCharacters: CharacterSet.controlCharacters.inverted)
let xml = try! XML.parse(str2!)
print(xml["xmlopening"].text!.removingPercentEncoding!) // -> "@ß123\u{1C}"
```

**Comment by kazuhiro4949** [comment]
I updated this library to support the invalid character error.
