### ISSUE TITLE
How can get the raw XML?

### ISSUE THREAD

**Issue by haskins-io** [yahoojapan/SwiftyXMLParser#28]
Hi,

a couple of people have asked the same question, but I don't think there has been a satisfactory answer, unless I've missed it.

Lets say I want to parse some XML : [AWS EC2 API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html#API_DescribeInstances_Examples)

I get the results back and do something like this `let instances = XML.parse(response)`

Now I want to iterate around the returned objects so I do this:
```
for instance in instances["DescribeInstancesResponse", "reservationSet", "item", "instancesSet", "item"] {

}
```
What I want to do is store the information in Core Data, and because the elements of the XML Instance Item could change over time all I'm going to do is put the whole XML into the database so I don't need to worry about constantly updating the Managed Object model.

How can I get the original XML for the `instance` variable from the above example?

* I've tried instance.text - this just returns a lot of "\r"
* I've tried this `print(String(data: data, encoding: .utf8)!)` but I'm told that XML.Access is not convertible to Data

Is there a way of getting XML from an Accessor?

Thanks,

Mark

**Comment by kazuhiro4949** [comment]
@githublemming 
I'm sorry for late reply. 
There is no feature to write raw XML in Accessor.
SwiftyXMLParser only supports parsing XML.
So instance.text returns text in "instance" element.

But it may be important to support reproducing raw XML. 
We will make issue to discuss that.

Thanks

**Comment by haskins-io** [comment]
Hi,

Not a problem.

Thanks
