### ISSUE TITLE
New feature to generate a xml document from XML::Accessor

### ISSUE THREAD

**Issue by kazuhiro4949** [yahoojapan/SwiftyXMLParser#30]
SwiftyXMLParser only supports parsing XML.

But it may be helpful to support reproducing raw XML.
Have the discussion here.

https://github.com/yahoojapan/SwiftyXMLParser/issues/28

**Comment by pranay-thales** [comment]
Hello I am using SwiftyXMLParser and need help in generating RawXML from Accessor. But i am not finding any solution to achieve it. Can you please suggest how to start on this.

Thanks in advance.
