### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by RomaSafin** [yahoojapan/SwiftyXMLParser#46]
Due apple introduced SPM support natively in Xcode 11, will the project be updated to SPM support? And should we expect it soon or it's long term, low priority task ?

**Comment by kazuhiro4949** [comment]
Hi, @RomaSafin.

> will the project be updated to SPM support?

Yes, we will.  @rubengarciam gave us pull request to support SPM. 

https://github.com/yahoojapan/SwiftyXMLParser/pull/45

I will merge it after fixing a little conflict.

**Comment by RomaSafin** [comment]
Great. Sorry for duplicating. Haven't understood it was about the same.
