### ISSUE TITLE
Problem with parsing XML!

### ISSUE THREAD

**Issue by MagDA1906** [yahoojapan/SwiftyXMLParser#48]
Hello! I use SwiftyXMLParser in conjunction with Alamofier. I need to parse XML data from the news feed, for example lenta.ru/rss. The problem is in this piece of code, on line 7:

1 AF.request (url) .response { (response) in
2              if let data = response.data {
3                     let xml = XML.parse (data)
4                     var itemNumber = 0
5                     while xml.rss.channel.item [itemNumber] .text! = nil {
6                             self.newsModel = NewsModel ()
7                             self.newsModel.newsDescription = xml.rss.channel.item[itemNumber].description.text ?? ""
8                             self.models.append (self.newsModel)
9                             itemNumber + = 1
10                     }
11                      completion (self.models)
12             }
13 }

"description" in line 7 is a complete description of the news, but this parameter is reserved in your API.
Is there any way around this point?

**Comment by kazuhiro4949** [comment]
Hi, @MagDA1906 :)
```description``` is reserved in Swift language specification.
So you cannot use the keyword as a dynamic property.
Instead of that, you can use ```subscript``` as follows.

```swift
xml.rss.channel.item[itemNumber]["description"].text 
// or
xml.rss.channel.item[itemNumber, "description"].text 
```

**Comment by MagDA1906** [comment]
Hello! Thanks, I figured it out!

вс, 5 апр. 2020 г. в 14:32, Kazuhiro Hayashi <notifications@github.com>:
