### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by sirajl** [yahoojapan/SwiftyXMLParser#52]
I'm using Swift 5 however this would apply to earlier versions.

from NSData
- let data = str.data(using: .utf8)
Should be
- let string = String(decoding: data, as: UTF8.self)

**Comment by kazuhiro4949** [comment]
Thanks! I fixed it.

https://github.com/yahoojapan/SwiftyXMLParser/commit/5009f14af051cc8e0f20957375deb709f7b53758
