### ISSUE TITLE
IPHONEOS_DEPLOYMENT_TARGET

### ISSUE THREAD

**Issue by marinofaggiana** [yahoojapan/SwiftyXMLParser#55]
Hi,
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

**Comment by kazuhiro4949** [comment]
Thanks for your report. The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0 in 5.3.0
https://github.com/yahoojapan/SwiftyXMLParser/releases/tag/5.3.0
