### ISSUE TITLE
`SwiftyXMLParser` does not specify a Swift version 

### ISSUE THREAD

**Issue by gunhansancar** [yahoojapan/SwiftyXMLParser#58]
Hi there,

Error message:
_- `SwiftyXMLParser` does not specify a Swift version and none of the targets (`UnityFramework`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod._

This becomes a real issue for us. Especially when the project files are auto-generated on certain platforms e.g. Unity. 

The solution is to set the `swift_version` in the podspec file which should be strait forward.
https://guides.cocoapods.org/syntax/podspec.html

**Comment by SergiiSopin** [comment]
I have the same issue:

```
Installing SwiftyXMLParser (5.1.0)
[!] Unable to determine Swift version for the following pods:

- `SwiftyXMLParser` does not specify a Swift version and none of the targets (`Pods`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by kazuhiro4949** [comment]
I'm sorry for late reply. I fixed the issue. Could you try the new version?
