### ISSUE TITLE
Add support for CDATA

### ISSUE THREAD

**Issue by EthanLipnik** [yahoojapan/SwiftyXMLParser#60]
Hi, I want to be able to add HTML to my XML file but it can't parse it anymore. Adding CDATA elements fixes this but this framework doesn't seem to support that. I've had to use Base64 instead but that uses more storage and processing so hopefully this can be improved.
Thanks

**Comment by kazuhiro4949** [comment]
I'm sorry for late reply. We are planning to update the implementation. thanks :)

**Comment by EthanLipnik** [comment]
Thanks!

– Ethan Lipnik

**Comment by kazuhiro4949** [comment]
5.4.0 supports CDATA
