### ISSUE TITLE
Manually installation

### ISSUE THREAD

**Issue by Rufy86** [yahoojapan/SwiftyXMLParser#7]
How can I install this framework manually?

**Comment by kazuhiro4949** [comment]
You can manually build this library with the branch tagged "3.0.2", and drag and drop the .framework file to your project.
https://github.com/yahoojapan/SwiftyXMLParser/tree/3.0.2

**Comment by kazuhiro4949** [comment]
@Rufy86
If you have some trouble, reopen this issue :)
